### ISSUE TITLE
Dungeon loot tables empty

### ISSUE THREAD

**Issue by RoselinaFey** [The-Nexus-Project/Limitless#3] opened 2019-10-12 14:26 UTC
Hello I've been playing on single-player for a while an a few patches and recently i found a buried treasure map. When i finally found it and opened it up it was completely empty. this was disheartening cause i was looking forever for a chance to get flying things materials. i later found a nether fortress and all the chests there were empty.
 I tested if it was the loot not just bad luck by using the _Enigmatic legacy_ item _The One Chest_ selecting both nether fortress and buried treasure putting them into the box and they were all empty, no loot. If there is something i can do please let me know its a real bummer and dont wanna have to cheat me an item just to fly on a carpet.

Sincerely,
RoselinaFey the builder of farms.

**Comment by Gbergz** [comment] 2019-10-12 17:37
Investigating, i'll get back to you once i have more info.
Thank you for the report!

EDIT: It appears you're right, loottables in the Nether fortresses are empty. Buried Treasure maps aswell, i'll try to figure it out.

**Comment by RoselinaFey** [comment] 2019-10-12 20:03
Yes it kinda breaks both enigmatic and flying things. I appreciate the speedy response

**Comment by hm-ysjiang** [comment] 2019-10-13 12:30
I am the author of PotionCapsule, and I think it is the cause of this issue. Sorry for causing this to happen.

The reason is some mods(including mine) forgot to set their loot pool's name while injecting it to the loot table, and this causes an exception thrown when another mod trying to add its own pool into the injected table.

I have received [an issue report](https://github.com/hm-ysjiang/PotionCapsule/issues/7) with some problematic mods listed.
Further details about this problem can be found [here](https://github.com/MysticMods/MysticalWorld/issues/71).

This bug is fixed in PotionCapsule 1.1.1.

**Comment by RoselinaFey** [comment] 2019-10-13 12:44
Please forgive me for this but the mods name is just too good. "PotionCapsule, I'm going into a dungeon and I need your finest loot tables. You can't handle my strongest loot bug."

**Comment by Gbergz** [comment] 2019-10-13 13:15
Heya, i've been busy trying "fix" this error. 
I've removed mods 1 by 1 until this problem went away. And it's now solved. 

I removed the mod [Magic Mirrors](https://www.curseforge.com/minecraft/mc-mods/magic-mirrors) and the problem went away, dungeon loottables are now back, try this for yourself. 

Remove the Magic Mirrors in the mods folder & then launch the game, create a new world, use command "/locate" to locate a structure with dungeon loot. Desert Pyramid for example, it should now have loot.

**Comment by Gbergz** [comment] 2019-10-13 13:16
> Please forgive me for this but the mods name is just too good. "PotionCapsule, I'm going into a dungeon and I need your finest loot tables. You can't handle my strongest loot bug."

Heya, i've been busy trying "fix" this error.
I've removed mods 1 by 1 until this problem went away. And it's now solved.

I removed the mod [Magic Mirrors](https://www.curseforge.com/minecraft/mc-mods/magic-mirrors) and the problem went away, dungeon loottables are now back, try this for yourself.

Remove the [Magic Mirrors](https://www.curseforge.com/minecraft/mc-mods/magic-mirrors) in the mods folder & then launch the game, create a new world, use command "/locate" to locate a structure with dungeon loot. Desert Pyramid for example, it should now have loot.

**Comment by Gbergz** [comment] 2019-10-13 21:48
This mod will either be fixed or removed next update. 
Re-open this issue if further issues appear.

**Closed as completed by Gbergz** 2019-10-13 21:48 UTC

**Comment by noobanidus** [comment] 2019-10-14 06:32
Quick note: `/setblock ~ ~ ~ chest{LootTable:"chests/simple_dungeon"}` will place the loot chest for a simple dungeon at your table. The main Minecraft (unofficial?) Wiki has a list of all the loot tables -- saves all the trouble of going out to find it when you can just spawn it directly under you.

**Comment by Gbergz** [comment] 2019-10-14 11:04
> Quick note: `/setblock ~ ~ ~ chest{LootTable:"chests/simple_dungeon"}` will place the loot chest for a simple dungeon at your table. The main Minecraft (unofficial?) Wiki has a list of all the loot tables -- saves all the trouble of going out to find it when you can just spawn it directly under you.

Thank you. :)

**Comment by noobanidus** [comment] 2019-10-14 22:40
(I also plan on updating my mod ["Loot Drop"](https://www.curseforge.com/minecraft/mc-mods/loot-drop) for 1.14 at some point in the near future.)
